### PR TITLE
fix: fix username update + active display of it

### LINKED ISSUE #207: Fix: username update in user's settings

### LINKED ISSUE #209: Fix: email update

### PR DESCRIPTION
**Pull request by christophechr**
## Description
[Description de la PR]
The username updated is pushed to server and active refresh of the data when the username is changed in the app

## Changement
[listes des additions / changement dans le projet]
- profile_page.dart
- settings_page.dart

## Commentaire
[Commentaire sur les évolutions ajoutées par la PR]
Username redondance ?

### CODE REVIEW

File: playfit-mobile/playfit/lib/profile_page.dart [hunk 1]
```diff
@@ -193,11 +195,14 @@ class _ProfilePageState extends State<ProfilePage> {
...
                 color: Colors.black,
-                onPressed: () {
-                  Navigator.push(
+                onPressed: () async {
+                  final result = await Navigator.push(
                     context,
                     MaterialPageRoute(builder: (_) => const SettingsPage()),
                   );
+                  if (result == true) {
+                    _load();
```
Comment (Eowiin) [inline playfit-mobile/playfit/lib/profile_page.dart:215]: Why call fetching user's data when you leave the page to go to setting's page ?

File: playfit-mobile/playfit/lib/settings_page.dart [hunk 2]
```diff
@@ -53,9 +55,35 @@ class _SettingsPageState extends State<SettingsPage> {
         boxTypeStr == 'bottom' ? UserBoxType.bottom : UserBoxType.left;
     _notificationsEnabled =
         await _notificationService.loadNotificationSettings();
+    
+    await _loadUserData();
+    
     setState(() {});
   }
 
+  Future<void> _loadUserData() async {
```
Comment (Eowiin) [inline playfit-mobile/playfit/lib/settings_page.dart]: Isn't it better to pass data as parameters from profile page instead of doing another api call ?

**Review by Eowiin — APPROVED** [review]
